title: VEDS-Group
description: Official documentation for VEDS-Group
theme: just-the-docs
url: https://veds-group.github.io
baseurl: ""

# Enable hierarchical navigation
nav_sort: case_insensitive

# GitHub Pages configuration
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
